[package]
name = "slsa-example"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["slsa", "supply-chain", "example"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
